/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessoesRouteImport } from './routes/sessoes'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorretoresRouteImport } from './routes/corretores'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRoute = SessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretoresRoute = CorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corretores'
    | '/dashboard'
    | '/fila'
    | '/sessoes'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corretores' | '/dashboard' | '/fila' | '/sessoes' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/corretores'
    | '/dashboard'
    | '/fila'
    | '/sessoes'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorretoresRoute: typeof CorretoresRoute
  DashboardRoute: typeof DashboardRoute
  FilaRoute: typeof FilaRoute
  SessoesRoute: typeof SessoesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretores': {
      id: '/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof CorretoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorretoresRoute: CorretoresRoute,
  DashboardRoute: DashboardRoute,
  FilaRoute: FilaRoute,
  SessoesRoute: SessoesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
