/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessoesRouteImport } from './routes/sessoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as FilaRouteImport } from './routes/fila'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorretoresRouteImport } from './routes/corretores'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedRedesignRouteImport } from './routes/_authenticated/redesign'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRoute = SessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FilaRoute = FilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretoresRoute = CorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedesignRoute = AuthenticatedRedesignRouteImport.update({
  id: '/redesign',
  path: '/redesign',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/redesign': typeof AuthenticatedRedesignRoute
  '/convite/$token': typeof ConviteTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/redesign': typeof AuthenticatedRedesignRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/corretores': typeof CorretoresRoute
  '/dashboard': typeof DashboardRoute
  '/fila': typeof FilaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sessoes': typeof SessoesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/redesign': typeof AuthenticatedRedesignRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/corretores'
    | '/dashboard'
    | '/fila'
    | '/reset-password'
    | '/sessoes'
    | '/sitemap.xml'
    | '/redesign'
    | '/convite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/corretores'
    | '/dashboard'
    | '/fila'
    | '/reset-password'
    | '/sessoes'
    | '/sitemap.xml'
    | '/redesign'
    | '/convite/$token'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/corretores'
    | '/dashboard'
    | '/fila'
    | '/reset-password'
    | '/sessoes'
    | '/sitemap.xml'
    | '/_authenticated/redesign'
    | '/convite/$token'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CorretoresRoute: typeof CorretoresRoute
  DashboardRoute: typeof DashboardRoute
  FilaRoute: typeof FilaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessoesRoute: typeof SessoesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fila': {
      id: '/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof FilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretores': {
      id: '/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof CorretoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redesign': {
      id: '/_authenticated/redesign'
      path: '/redesign'
      fullPath: '/redesign'
      preLoaderRoute: typeof AuthenticatedRedesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRedesignRoute: typeof AuthenticatedRedesignRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRedesignRoute: AuthenticatedRedesignRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CorretoresRoute: CorretoresRoute,
  DashboardRoute: DashboardRoute,
  FilaRoute: FilaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessoesRoute: SessoesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
